# Check https://circleci.com/docs/2.0/language-elixir/ for more details
version: 2
jobs:
  build:
    machine:
          image: "ubuntu-2004:202010-01"
          docker_layer_caching: false # not available on free plan

    working_directory: ~/repo
    steps:
      - checkout

      # specify any bash command here prefixed with `run: `
      - run:
          name: setup dev environment
          command: |
            export DEBIAN_FRONTEND=noninteractive

            # Install docker
            sudo apt-get remove docker docker-engine docker.io containerd runc
            sudo apt-get install apt-transport-https ca-certificates curl gnupg-agent software-properties-common
            curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
            sudo apt-key fingerprint 0EBFCD88
            sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
            sudo apt-get update
            sudo apt-get install docker-ce docker-ce-cli containerd.io

            # Setup elixir
            wget https://packages.erlang-solutions.com/erlang-solutions_2.0_all.deb
            sudo dpkg -i erlang-solutions_2.0_all.deb
            sudo apt-get update
            sudo apt-get install esl-erlang elixir git
            mix local.hex --force
            mix local.rebar --force

      - run: mix deps.get
      - run: mix credo
      - run: mix format --check-formatted
      - run: mix coveralls.post --trace -t $COVERALLS_REPO_TOKEN
