# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.Address do
  @moduledoc """
  Address represents an IPv4 or IPv6 IP address.
  """

  @derive [Poison.Encoder]
  defstruct [
    :Addr,
    :PrefixLen
  ]

  @type t :: %__MODULE__{
    :Addr => String.t | nil,
    :PrefixLen => integer() | nil
  }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.Address do
  def decode(value, _options) do
    value
  end
end

