# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.AuthConfig do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :username,
    :password,
    :email,
    :serveraddress
  ]

  @type t :: %__MODULE__{
    :username => String.t | nil,
    :password => String.t | nil,
    :email => String.t | nil,
    :serveraddress => String.t | nil
  }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.AuthConfig do
  def decode(value, _options) do
    value
  end
end

