# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.BuildInfo do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :stream,
    :error,
    :errorDetail,
    :status,
    :progress,
    :progressDetail,
    :aux
  ]

  @type t :: %__MODULE__{
    :id => String.t | nil,
    :stream => String.t | nil,
    :error => String.t | nil,
    :errorDetail => DockerEngineAPI.Model.ErrorDetail.t | nil,
    :status => String.t | nil,
    :progress => String.t | nil,
    :progressDetail => DockerEngineAPI.Model.ProgressDetail.t | nil,
    :aux => DockerEngineAPI.Model.ImageId.t | nil
  }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.BuildInfo do
  import DockerEngineAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:errorDetail, :struct, DockerEngineAPI.Model.ErrorDetail, options)
    |> deserialize(:progressDetail, :struct, DockerEngineAPI.Model.ProgressDetail, options)
    |> deserialize(:aux, :struct, DockerEngineAPI.Model.ImageId, options)
  end
end

