# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.Commit do
  @moduledoc """
  Commit holds the Git-commit (SHA1) that a binary was built from, as reported in the version-string of external tools, such as `containerd`, or `runC`. 
  """

  @derive [Poison.Encoder]
  defstruct [
    :ID,
    :Expected
  ]

  @type t :: %__MODULE__{
    :ID => String.t | nil,
    :Expected => String.t | nil
  }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.Commit do
  def decode(value, _options) do
    value
  end
end

