# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.Config do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :ID,
    :Version,
    :CreatedAt,
    :UpdatedAt,
    :Spec
  ]

  @type t :: %__MODULE__{
    :ID => String.t | nil,
    :Version => DockerEngineAPI.Model.ObjectVersion.t | nil,
    :CreatedAt => String.t | nil,
    :UpdatedAt => String.t | nil,
    :Spec => DockerEngineAPI.Model.ConfigSpec.t | nil
  }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.Config do
  import DockerEngineAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:Version, :struct, DockerEngineAPI.Model.ObjectVersion, options)
    |> deserialize(:Spec, :struct, DockerEngineAPI.Model.ConfigSpec, options)
  end
end

