# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.ContainerTopResponse do
  @moduledoc """
  OK response to ContainerTop operation
  """

  @derive [Poison.Encoder]
  defstruct [
    :Titles,
    :Processes
  ]

  @type t :: %__MODULE__{
    :Titles => [String.t] | nil,
    :Processes => [[String.t]] | nil
  }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.ContainerTopResponse do
  def decode(value, _options) do
    value
  end
end

