# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.ContainerSummaryNetworkSettings do
  @moduledoc """
  A summary of the container's network settings
  """

  @derive [Poison.Encoder]
  defstruct [
    :Networks
  ]

  @type t :: %__MODULE__{
    :Networks => %{optional(String.t) => DockerEngineAPI.Model.EndpointSettings.t} | nil
  }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.ContainerSummaryNetworkSettings do
  import DockerEngineAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:Networks, :map, DockerEngineAPI.Model.EndpointSettings, options)
  end
end

