# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.ContainerWaitExitError do
  @moduledoc """
  container waiting error, if any
  """

  @derive [Poison.Encoder]
  defstruct [
    :Message
  ]

  @type t :: %__MODULE__{
    :Message => String.t | nil
  }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.ContainerWaitExitError do
  def decode(value, _options) do
    value
  end
end

