# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.ContainerCreateRequestAllOf do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :HostConfig,
    :NetworkingConfig
  ]

  @type t :: %__MODULE__{
    :HostConfig => DockerEngineAPI.Model.HostConfig.t | nil,
    :NetworkingConfig => DockerEngineAPI.Model.NetworkingConfig.t | nil
  }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.ContainerCreateRequestAllOf do
  import DockerEngineAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:HostConfig, :struct, DockerEngineAPI.Model.HostConfig, options)
    |> deserialize(:NetworkingConfig, :struct, DockerEngineAPI.Model.NetworkingConfig, options)
  end
end

