# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.ContainerChangeResponseItem do
  @moduledoc """
  change item in response to ContainerChanges operation
  """

  @derive [Poison.Encoder]
  defstruct [
    :Path,
    :Kind
  ]

  @type t :: %__MODULE__{
    :Path => String.t,
    :Kind => integer()
  }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.ContainerChangeResponseItem do
  def decode(value, _options) do
    value
  end
end

