# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.ContainerSummaryHostConfig do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :NetworkMode
  ]

  @type t :: %__MODULE__{
    :NetworkMode => String.t | nil
  }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.ContainerSummaryHostConfig do
  def decode(value, _options) do
    value
  end
end

