# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.ContainerCreateResponse do
  @moduledoc """
  OK response to ContainerCreate operation
  """

  @derive [Poison.Encoder]
  defstruct [
    :Id,
    :Warnings
  ]

  @type t :: %__MODULE__{
    :Id => String.t,
    :Warnings => [String.t]
  }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.ContainerCreateResponse do
  def decode(value, _options) do
    value
  end
end

