# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.CreateImageInfo do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :error,
    :status,
    :progress,
    :progressDetail
  ]

  @type t :: %__MODULE__{
    :id => String.t | nil,
    :error => String.t | nil,
    :status => String.t | nil,
    :progress => String.t | nil,
    :progressDetail => DockerEngineAPI.Model.ProgressDetail.t | nil
  }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.CreateImageInfo do
  import DockerEngineAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:progressDetail, :struct, DockerEngineAPI.Model.ProgressDetail, options)
  end
end

