# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.DistributionInspect do
  @moduledoc """
  Describes the result obtained from contacting the registry to retrieve image metadata. 
  """

  @derive [Poison.Encoder]
  defstruct [
    :Descriptor,
    :Platforms
  ]

  @type t :: %__MODULE__{
    :Descriptor => DockerEngineAPI.Model.OciDescriptor.t,
    :Platforms => [DockerEngineAPI.Model.OciPlatform.t]
  }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.DistributionInspect do
  import DockerEngineAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:Descriptor, :struct, DockerEngineAPI.Model.OciDescriptor, options)
    |> deserialize(:Platforms, :list, DockerEngineAPI.Model.OciPlatform, options)
  end
end

