# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.Driver do
  @moduledoc """
  Driver represents a driver (network, logging, secrets).
  """

  @derive [Poison.Encoder]
  defstruct [
    :Name,
    :Options
  ]

  @type t :: %__MODULE__{
    :Name => String.t,
    :Options => %{optional(String.t) => String.t} | nil
  }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.Driver do
  def decode(value, _options) do
    value
  end
end

