# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.EndpointSpec do
  @moduledoc """
  Properties that can be configured to access and load balance a service.
  """

  @derive [Poison.Encoder]
  defstruct [
    :Mode,
    :Ports
  ]

  @type t :: %__MODULE__{
    :Mode => String.t | nil,
    :Ports => [DockerEngineAPI.Model.EndpointPortConfig.t] | nil
  }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.EndpointSpec do
  import DockerEngineAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:Ports, :list, DockerEngineAPI.Model.EndpointPortConfig, options)
  end
end

