# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.EndpointPortConfig do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :Name,
    :Protocol,
    :TargetPort,
    :PublishedPort,
    :PublishMode
  ]

  @type t :: %__MODULE__{
    :Name => String.t | nil,
    :Protocol => String.t | nil,
    :TargetPort => integer() | nil,
    :PublishedPort => integer() | nil,
    :PublishMode => String.t | nil
  }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.EndpointPortConfig do
  def decode(value, _options) do
    value
  end
end

