# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.EngineDescription do
  @moduledoc """
  EngineDescription provides information about an engine.
  """

  @derive [Poison.Encoder]
  defstruct [
    :EngineVersion,
    :Labels,
    :Plugins
  ]

  @type t :: %__MODULE__{
    :EngineVersion => String.t | nil,
    :Labels => %{optional(String.t) => String.t} | nil,
    :Plugins => [DockerEngineAPI.Model.EngineDescriptionPluginsInner.t] | nil
  }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.EngineDescription do
  import DockerEngineAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:Plugins, :list, DockerEngineAPI.Model.EngineDescriptionPluginsInner, options)
  end
end

