# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.EngineDescriptionPluginsInner do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :Type,
    :Name
  ]

  @type t :: %__MODULE__{
    :Type => String.t | nil,
    :Name => String.t | nil
  }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.EngineDescriptionPluginsInner do
  def decode(value, _options) do
    value
  end
end

