# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.ErrorResponse do
  @moduledoc """
  Represents an error.
  """

  @derive [Poison.Encoder]
  defstruct [
    :message
  ]

  @type t :: %__MODULE__{
    :message => String.t
  }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.ErrorResponse do
  def decode(value, _options) do
    value
  end
end

