# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.EventMessage do
  @moduledoc """
  EventMessage represents the information an event contains. 
  """

  @derive [Poison.Encoder]
  defstruct [
    :Type,
    :Action,
    :Actor,
    :scope,
    :time,
    :timeNano
  ]

  @type t :: %__MODULE__{
    :Type => String.t | nil,
    :Action => String.t | nil,
    :Actor => DockerEngineAPI.Model.EventActor.t | nil,
    :scope => String.t | nil,
    :time => integer() | nil,
    :timeNano => integer() | nil
  }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.EventMessage do
  import DockerEngineAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:Actor, :struct, DockerEngineAPI.Model.EventActor, options)
  end
end

