# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.ExecConfig do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :AttachStdin,
    :AttachStdout,
    :AttachStderr,
    :DetachKeys,
    :Tty,
    :Env,
    :Cmd,
    :Privileged,
    :User,
    :WorkingDir
  ]

  @type t :: %__MODULE__{
    :AttachStdin => boolean() | nil,
    :AttachStdout => boolean() | nil,
    :AttachStderr => boolean() | nil,
    :DetachKeys => String.t | nil,
    :Tty => boolean() | nil,
    :Env => [String.t] | nil,
    :Cmd => [String.t] | nil,
    :Privileged => boolean() | nil,
    :User => String.t | nil,
    :WorkingDir => String.t | nil
  }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.ExecConfig do
  def decode(value, _options) do
    value
  end
end

