# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.GraphDriverData do
  @moduledoc """
  Information about the storage driver used to store the container's and image's filesystem. 
  """

  @derive [Poison.Encoder]
  defstruct [
    :Name,
    :Data
  ]

  @type t :: %__MODULE__{
    :Name => String.t,
    :Data => %{optional(String.t) => String.t}
  }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.GraphDriverData do
  def decode(value, _options) do
    value
  end
end

