# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.HealthConfig do
  @moduledoc """
  A test to perform to check that the container is healthy.
  """

  @derive [Poison.Encoder]
  defstruct [
    :Test,
    :Interval,
    :Timeout,
    :Retries,
    :StartPeriod
  ]

  @type t :: %__MODULE__{
    :Test => [String.t] | nil,
    :Interval => integer() | nil,
    :Timeout => integer() | nil,
    :Retries => integer() | nil,
    :StartPeriod => integer() | nil
  }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.HealthConfig do
  def decode(value, _options) do
    value
  end
end

