# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.HistoryResponseItem do
  @moduledoc """
  individual image layer information in response to ImageHistory operation
  """

  @derive [Poison.Encoder]
  defstruct [
    :Id,
    :Created,
    :CreatedBy,
    :Tags,
    :Size,
    :Comment
  ]

  @type t :: %__MODULE__{
    :Id => String.t,
    :Created => integer(),
    :CreatedBy => String.t,
    :Tags => [String.t],
    :Size => integer(),
    :Comment => String.t
  }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.HistoryResponseItem do
  def decode(value, _options) do
    value
  end
end

