# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.HostConfigAllOfLogConfig do
  @moduledoc """
  The logging configuration for this container
  """

  @derive [Poison.Encoder]
  defstruct [
    :Type,
    :Config
  ]

  @type t :: %__MODULE__{
    :Type => String.t | nil,
    :Config => %{optional(String.t) => String.t} | nil
  }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.HostConfigAllOfLogConfig do
  def decode(value, _options) do
    value
  end
end

