# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.IdResponse do
  @moduledoc """
  Response to an API call that returns just an Id
  """

  @derive [Poison.Encoder]
  defstruct [
    :Id
  ]

  @type t :: %__MODULE__{
    :Id => String.t
  }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.IdResponse do
  def decode(value, _options) do
    value
  end
end

