# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.ImagePruneResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :ImagesDeleted,
    :SpaceReclaimed
  ]

  @type t :: %__MODULE__{
    :ImagesDeleted => [DockerEngineAPI.Model.ImageDeleteResponseItem.t] | nil,
    :SpaceReclaimed => integer() | nil
  }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.ImagePruneResponse do
  import DockerEngineAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:ImagesDeleted, :list, DockerEngineAPI.Model.ImageDeleteResponseItem, options)
  end
end

