# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.ImageId do
  @moduledoc """
  Image ID or Digest
  """

  @derive [Poison.Encoder]
  defstruct [
    :ID
  ]

  @type t :: %__MODULE__{
    :ID => String.t | nil
  }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.ImageId do
  def decode(value, _options) do
    value
  end
end

