# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.ImageSearchResponseItem do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :description,
    :is_official,
    :is_automated,
    :name,
    :star_count
  ]

  @type t :: %__MODULE__{
    :description => String.t | nil,
    :is_official => boolean() | nil,
    :is_automated => boolean() | nil,
    :name => String.t | nil,
    :star_count => integer() | nil
  }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.ImageSearchResponseItem do
  def decode(value, _options) do
    value
  end
end

