# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.ImageDeleteResponseItem do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :Untagged,
    :Deleted
  ]

  @type t :: %__MODULE__{
    :Untagged => String.t | nil,
    :Deleted => String.t | nil
  }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.ImageDeleteResponseItem do
  def decode(value, _options) do
    value
  end
end

