# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.ImageInspectRootFs do
  @moduledoc """
  Information about the image's RootFS, including the layer IDs. 
  """

  @derive [Poison.Encoder]
  defstruct [
    :Type,
    :Layers
  ]

  @type t :: %__MODULE__{
    :Type => String.t,
    :Layers => [String.t] | nil
  }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.ImageInspectRootFs do
  def decode(value, _options) do
    value
  end
end

