# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.IndexInfo do
  @moduledoc """
  IndexInfo contains information about a registry.
  """

  @derive [Poison.Encoder]
  defstruct [
    :Name,
    :Mirrors,
    :Secure,
    :Official
  ]

  @type t :: %__MODULE__{
    :Name => String.t | nil,
    :Mirrors => [String.t] | nil,
    :Secure => boolean() | nil,
    :Official => boolean() | nil
  }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.IndexInfo do
  def decode(value, _options) do
    value
  end
end

