# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.Ipam do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :Driver,
    :Config,
    :Options
  ]

  @type t :: %__MODULE__{
    :Driver => String.t | nil,
    :Config => [DockerEngineAPI.Model.IpamConfig.t] | nil,
    :Options => %{optional(String.t) => String.t} | nil
  }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.Ipam do
  import DockerEngineAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:Config, :list, DockerEngineAPI.Model.IpamConfig, options)
  end
end

