# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.IpamConfig do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :Subnet,
    :IPRange,
    :Gateway,
    :AuxiliaryAddresses
  ]

  @type t :: %__MODULE__{
    :Subnet => String.t | nil,
    :IPRange => String.t | nil,
    :Gateway => String.t | nil,
    :AuxiliaryAddresses => %{optional(String.t) => String.t} | nil
  }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.IpamConfig do
  def decode(value, _options) do
    value
  end
end

