# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.JoinTokens do
  @moduledoc """
  JoinTokens contains the tokens workers and managers need to join the swarm. 
  """

  @derive [Poison.Encoder]
  defstruct [
    :Worker,
    :Manager
  ]

  @type t :: %__MODULE__{
    :Worker => String.t | nil,
    :Manager => String.t | nil
  }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.JoinTokens do
  def decode(value, _options) do
    value
  end
end

