# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.LocalNodeState do
  @moduledoc """
  Current local status of this node.
  """

  @derive [Poison.Encoder]
  defstruct [
    
  ]

  @type t :: %__MODULE__{
    
  }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.LocalNodeState do
  def decode(value, _options) do
    value
  end
end

