# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.MountPoint do
  @moduledoc """
  MountPoint represents a mount point configuration inside the container. This is used for reporting the mountpoints in use by a container. 
  """

  @derive [Poison.Encoder]
  defstruct [
    :Type,
    :Name,
    :Source,
    :Destination,
    :Driver,
    :Mode,
    :RW,
    :Propagation
  ]

  @type t :: %__MODULE__{
    :Type => String.t | nil,
    :Name => String.t | nil,
    :Source => String.t | nil,
    :Destination => String.t | nil,
    :Driver => String.t | nil,
    :Mode => String.t | nil,
    :RW => boolean() | nil,
    :Propagation => String.t | nil
  }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.MountPoint do
  def decode(value, _options) do
    value
  end
end

