# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.Mount do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :Target,
    :Source,
    :Type,
    :ReadOnly,
    :Consistency,
    :BindOptions,
    :VolumeOptions,
    :TmpfsOptions
  ]

  @type t :: %__MODULE__{
    :Target => String.t | nil,
    :Source => String.t | nil,
    :Type => String.t | nil,
    :ReadOnly => boolean() | nil,
    :Consistency => String.t | nil,
    :BindOptions => DockerEngineAPI.Model.MountBindOptions.t | nil,
    :VolumeOptions => DockerEngineAPI.Model.MountVolumeOptions.t | nil,
    :TmpfsOptions => DockerEngineAPI.Model.MountTmpfsOptions.t | nil
  }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.Mount do
  import DockerEngineAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:BindOptions, :struct, DockerEngineAPI.Model.MountBindOptions, options)
    |> deserialize(:VolumeOptions, :struct, DockerEngineAPI.Model.MountVolumeOptions, options)
    |> deserialize(:TmpfsOptions, :struct, DockerEngineAPI.Model.MountTmpfsOptions, options)
  end
end

