# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.MountBindOptions do
  @moduledoc """
  Optional configuration for the `bind` type.
  """

  @derive [Poison.Encoder]
  defstruct [
    :Propagation,
    :NonRecursive
  ]

  @type t :: %__MODULE__{
    :Propagation => String.t | nil,
    :NonRecursive => boolean() | nil
  }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.MountBindOptions do
  def decode(value, _options) do
    value
  end
end

