# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.MountVolumeOptions do
  @moduledoc """
  Optional configuration for the `volume` type.
  """

  @derive [Poison.Encoder]
  defstruct [
    :NoCopy,
    :Labels,
    :DriverConfig
  ]

  @type t :: %__MODULE__{
    :NoCopy => boolean() | nil,
    :Labels => %{optional(String.t) => String.t} | nil,
    :DriverConfig => DockerEngineAPI.Model.MountVolumeOptionsDriverConfig.t | nil
  }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.MountVolumeOptions do
  import DockerEngineAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:DriverConfig, :struct, DockerEngineAPI.Model.MountVolumeOptionsDriverConfig, options)
  end
end

