# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.MountVolumeOptionsDriverConfig do
  @moduledoc """
  Map of driver specific options
  """

  @derive [Poison.Encoder]
  defstruct [
    :Name,
    :Options
  ]

  @type t :: %__MODULE__{
    :Name => String.t | nil,
    :Options => %{optional(String.t) => String.t} | nil
  }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.MountVolumeOptionsDriverConfig do
  def decode(value, _options) do
    value
  end
end

