# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.MountTmpfsOptions do
  @moduledoc """
  Optional configuration for the `tmpfs` type.
  """

  @derive [Poison.Encoder]
  defstruct [
    :SizeBytes,
    :Mode
  ]

  @type t :: %__MODULE__{
    :SizeBytes => integer() | nil,
    :Mode => integer() | nil
  }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.MountTmpfsOptions do
  def decode(value, _options) do
    value
  end
end

