# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.NetworkAttachmentConfig do
  @moduledoc """
  Specifies how a service should be attached to a particular network. 
  """

  @derive [Poison.Encoder]
  defstruct [
    :Target,
    :Aliases,
    :DriverOpts
  ]

  @type t :: %__MODULE__{
    :Target => String.t | nil,
    :Aliases => [String.t] | nil,
    :DriverOpts => %{optional(String.t) => String.t} | nil
  }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.NetworkAttachmentConfig do
  def decode(value, _options) do
    value
  end
end

