# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.NetworkDisconnectRequest do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :Container,
    :EndpointConfig
  ]

  @type t :: %__MODULE__{
    :Container => String.t | nil,
    :EndpointConfig => DockerEngineAPI.Model.EndpointSettings.t | nil
  }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.NetworkDisconnectRequest do
  import DockerEngineAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:EndpointConfig, :struct, DockerEngineAPI.Model.EndpointSettings, options)
  end
end

