# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.NetworkConnectRequest do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :Container,
    :Force
  ]

  @type t :: %__MODULE__{
    :Container => String.t | nil,
    :Force => boolean() | nil
  }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.NetworkConnectRequest do
  def decode(value, _options) do
    value
  end
end

