# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.NodeDescription do
  @moduledoc """
  NodeDescription encapsulates the properties of the Node as reported by the agent. 
  """

  @derive [Poison.Encoder]
  defstruct [
    :Hostname,
    :Platform,
    :Resources,
    :Engine,
    :TLSInfo
  ]

  @type t :: %__MODULE__{
    :Hostname => String.t | nil,
    :Platform => DockerEngineAPI.Model.Platform.t | nil,
    :Resources => DockerEngineAPI.Model.ResourceObject.t | nil,
    :Engine => DockerEngineAPI.Model.EngineDescription.t | nil,
    :TLSInfo => DockerEngineAPI.Model.TlsInfo.t | nil
  }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.NodeDescription do
  import DockerEngineAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:Platform, :struct, DockerEngineAPI.Model.Platform, options)
    |> deserialize(:Resources, :struct, DockerEngineAPI.Model.ResourceObject, options)
    |> deserialize(:Engine, :struct, DockerEngineAPI.Model.EngineDescription, options)
    |> deserialize(:TLSInfo, :struct, DockerEngineAPI.Model.TlsInfo, options)
  end
end

