# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.NodeStatus do
  @moduledoc """
  NodeStatus represents the status of a node.  It provides the current status of the node, as seen by the manager. 
  """

  @derive [Poison.Encoder]
  defstruct [
    :State,
    :Message,
    :Addr
  ]

  @type t :: %__MODULE__{
    :State => DockerEngineAPI.Model.NodeState.t | nil,
    :Message => String.t | nil,
    :Addr => String.t | nil
  }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.NodeStatus do
  import DockerEngineAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:State, :struct, DockerEngineAPI.Model.NodeState, options)
  end
end

