# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.NodeSpec do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :Name,
    :Labels,
    :Role,
    :Availability
  ]

  @type t :: %__MODULE__{
    :Name => String.t | nil,
    :Labels => %{optional(String.t) => String.t} | nil,
    :Role => String.t | nil,
    :Availability => String.t | nil
  }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.NodeSpec do
  def decode(value, _options) do
    value
  end
end

