# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.ObjectVersion do
  @moduledoc """
  The version number of the object such as node, service, etc. This is needed to avoid conflicting writes. The client must send the version number along with the modified specification when updating these objects.  This approach ensures safe concurrency and determinism in that the change on the object may not be applied if the version number has changed from the last read. In other words, if two update requests specify the same base version, only one of the requests can succeed. As a result, two separate update requests that happen at the same time will not unintentionally overwrite each other. 
  """

  @derive [Poison.Encoder]
  defstruct [
    :Index
  ]

  @type t :: %__MODULE__{
    :Index => integer() | nil
  }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.ObjectVersion do
  def decode(value, _options) do
    value
  end
end

