# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.PeerNode do
  @moduledoc """
  Represents a peer-node in the swarm
  """

  @derive [Poison.Encoder]
  defstruct [
    :NodeID,
    :Addr
  ]

  @type t :: %__MODULE__{
    :NodeID => String.t | nil,
    :Addr => String.t | nil
  }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.PeerNode do
  def decode(value, _options) do
    value
  end
end

