# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.PluginPrivilege do
  @moduledoc """
  Describes a permission the user has to accept upon installing the plugin. 
  """

  @derive [Poison.Encoder]
  defstruct [
    :Name,
    :Description,
    :Value
  ]

  @type t :: %__MODULE__{
    :Name => String.t | nil,
    :Description => String.t | nil,
    :Value => [String.t] | nil
  }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.PluginPrivilege do
  def decode(value, _options) do
    value
  end
end

