# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.PluginConfigRootfs do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :type,
    :diff_ids
  ]

  @type t :: %__MODULE__{
    :type => String.t | nil,
    :diff_ids => [String.t] | nil
  }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.PluginConfigRootfs do
  def decode(value, _options) do
    value
  end
end

