# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.PluginInterfaceType do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :Prefix,
    :Capability,
    :Version
  ]

  @type t :: %__MODULE__{
    :Prefix => String.t,
    :Capability => String.t,
    :Version => String.t
  }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.PluginInterfaceType do
  def decode(value, _options) do
    value
  end
end

