# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.PluginConfigNetwork do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :Type
  ]

  @type t :: %__MODULE__{
    :Type => String.t
  }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.PluginConfigNetwork do
  def decode(value, _options) do
    value
  end
end

