# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.PluginConfigLinux do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :Capabilities,
    :AllowAllDevices,
    :Devices
  ]

  @type t :: %__MODULE__{
    :Capabilities => [String.t],
    :AllowAllDevices => boolean(),
    :Devices => [DockerEngineAPI.Model.PluginDevice.t]
  }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.PluginConfigLinux do
  import DockerEngineAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:Devices, :list, DockerEngineAPI.Model.PluginDevice, options)
  end
end

