# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.PluginConfigUser do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :UID,
    :GID
  ]

  @type t :: %__MODULE__{
    :UID => integer() | nil,
    :GID => integer() | nil
  }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.PluginConfigUser do
  def decode(value, _options) do
    value
  end
end

