# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.Plugin do
  @moduledoc """
  A plugin for the Engine API
  """

  @derive [Poison.Encoder]
  defstruct [
    :Id,
    :Name,
    :Enabled,
    :Settings,
    :PluginReference,
    :Config
  ]

  @type t :: %__MODULE__{
    :Id => String.t | nil,
    :Name => String.t,
    :Enabled => boolean(),
    :Settings => DockerEngineAPI.Model.PluginSettings.t,
    :PluginReference => String.t | nil,
    :Config => DockerEngineAPI.Model.PluginConfig.t
  }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.Plugin do
  import DockerEngineAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:Settings, :struct, DockerEngineAPI.Model.PluginSettings, options)
    |> deserialize(:Config, :struct, DockerEngineAPI.Model.PluginConfig, options)
  end
end

