# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.Port do
  @moduledoc """
  An open port on a container
  """

  @derive [Poison.Encoder]
  defstruct [
    :IP,
    :PrivatePort,
    :PublicPort,
    :Type
  ]

  @type t :: %__MODULE__{
    :IP => String.t | nil,
    :PrivatePort => integer(),
    :PublicPort => integer() | nil,
    :Type => String.t
  }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.Port do
  def decode(value, _options) do
    value
  end
end

