# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.PortBinding do
  @moduledoc """
  PortBinding represents a binding between a host IP address and a host port. 
  """

  @derive [Poison.Encoder]
  defstruct [
    :HostIp,
    :HostPort
  ]

  @type t :: %__MODULE__{
    :HostIp => String.t | nil,
    :HostPort => String.t | nil
  }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.PortBinding do
  def decode(value, _options) do
    value
  end
end

