# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.ProcessConfig do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :privileged,
    :user,
    :tty,
    :entrypoint,
    :arguments
  ]

  @type t :: %__MODULE__{
    :privileged => boolean() | nil,
    :user => String.t | nil,
    :tty => boolean() | nil,
    :entrypoint => String.t | nil,
    :arguments => [String.t] | nil
  }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.ProcessConfig do
  def decode(value, _options) do
    value
  end
end

