# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.ProgressDetail do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :current,
    :total
  ]

  @type t :: %__MODULE__{
    :current => integer() | nil,
    :total => integer() | nil
  }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.ProgressDetail do
  def decode(value, _options) do
    value
  end
end

