# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.RegistryServiceConfig do
  @moduledoc """
  RegistryServiceConfig stores daemon registry services configuration. 
  """

  @derive [Poison.Encoder]
  defstruct [
    :AllowNondistributableArtifactsCIDRs,
    :AllowNondistributableArtifactsHostnames,
    :InsecureRegistryCIDRs,
    :IndexConfigs,
    :Mirrors
  ]

  @type t :: %__MODULE__{
    :AllowNondistributableArtifactsCIDRs => [String.t] | nil,
    :AllowNondistributableArtifactsHostnames => [String.t] | nil,
    :InsecureRegistryCIDRs => [String.t] | nil,
    :IndexConfigs => %{optional(String.t) => DockerEngineAPI.Model.IndexInfo.t} | nil,
    :Mirrors => [String.t] | nil
  }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.RegistryServiceConfig do
  import DockerEngineAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:IndexConfigs, :map, DockerEngineAPI.Model.IndexInfo, options)
  end
end

