# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.ResourcesBlkioWeightDeviceInner do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :Path,
    :Weight
  ]

  @type t :: %__MODULE__{
    :Path => String.t | nil,
    :Weight => integer() | nil
  }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.ResourcesBlkioWeightDeviceInner do
  def decode(value, _options) do
    value
  end
end

