# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.ResourceObject do
  @moduledoc """
  An object describing the resources which can be advertised by a node and requested by a task. 
  """

  @derive [Poison.Encoder]
  defstruct [
    :NanoCPUs,
    :MemoryBytes,
    :GenericResources
  ]

  @type t :: %__MODULE__{
    :NanoCPUs => integer() | nil,
    :MemoryBytes => integer() | nil,
    :GenericResources => [DockerEngineAPI.Model.GenericResourcesInner.t] | nil
  }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.ResourceObject do
  import DockerEngineAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:GenericResources, :list, DockerEngineAPI.Model.GenericResourcesInner, options)
  end
end

