# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.ServiceSpecMode do
  @moduledoc """
  Scheduling mode for the service.
  """

  @derive [Poison.Encoder]
  defstruct [
    :Replicated,
    :Global,
    :ReplicatedJob,
    :GlobalJob
  ]

  @type t :: %__MODULE__{
    :Replicated => DockerEngineAPI.Model.ServiceSpecModeReplicated.t | nil,
    :Global => map() | nil,
    :ReplicatedJob => DockerEngineAPI.Model.ServiceSpecModeReplicatedJob.t | nil,
    :GlobalJob => map() | nil
  }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.ServiceSpecMode do
  import DockerEngineAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:Replicated, :struct, DockerEngineAPI.Model.ServiceSpecModeReplicated, options)
    |> deserialize(:ReplicatedJob, :struct, DockerEngineAPI.Model.ServiceSpecModeReplicatedJob, options)
  end
end

