# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.ServiceJobStatus do
  @moduledoc """
  The status of the service when it is in one of ReplicatedJob or GlobalJob modes. Absent on Replicated and Global mode services. The JobIteration is an ObjectVersion, but unlike the Service's version, does not need to be sent with an update request. 
  """

  @derive [Poison.Encoder]
  defstruct [
    :JobIteration,
    :LastExecution
  ]

  @type t :: %__MODULE__{
    :JobIteration => DockerEngineAPI.Model.ObjectVersion.t | nil,
    :LastExecution => String.t | nil
  }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.ServiceJobStatus do
  import DockerEngineAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:JobIteration, :struct, DockerEngineAPI.Model.ObjectVersion, options)
  end
end

