# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.ServiceCreateResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :ID,
    :Warning
  ]

  @type t :: %__MODULE__{
    :ID => String.t | nil,
    :Warning => String.t | nil
  }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.ServiceCreateResponse do
  def decode(value, _options) do
    value
  end
end

