# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.Service do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :ID,
    :Version,
    :CreatedAt,
    :UpdatedAt,
    :Spec,
    :Endpoint,
    :UpdateStatus,
    :ServiceStatus,
    :JobStatus
  ]

  @type t :: %__MODULE__{
    :ID => String.t | nil,
    :Version => DockerEngineAPI.Model.ObjectVersion.t | nil,
    :CreatedAt => String.t | nil,
    :UpdatedAt => String.t | nil,
    :Spec => DockerEngineAPI.Model.ServiceSpec.t | nil,
    :Endpoint => DockerEngineAPI.Model.ServiceEndpoint.t | nil,
    :UpdateStatus => DockerEngineAPI.Model.ServiceUpdateStatus.t | nil,
    :ServiceStatus => DockerEngineAPI.Model.ServiceServiceStatus.t | nil,
    :JobStatus => DockerEngineAPI.Model.ServiceJobStatus.t | nil
  }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.Service do
  import DockerEngineAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:Version, :struct, DockerEngineAPI.Model.ObjectVersion, options)
    |> deserialize(:Spec, :struct, DockerEngineAPI.Model.ServiceSpec, options)
    |> deserialize(:Endpoint, :struct, DockerEngineAPI.Model.ServiceEndpoint, options)
    |> deserialize(:UpdateStatus, :struct, DockerEngineAPI.Model.ServiceUpdateStatus, options)
    |> deserialize(:ServiceStatus, :struct, DockerEngineAPI.Model.ServiceServiceStatus, options)
    |> deserialize(:JobStatus, :struct, DockerEngineAPI.Model.ServiceJobStatus, options)
  end
end

