# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.ServiceEndpoint do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :Spec,
    :Ports,
    :VirtualIPs
  ]

  @type t :: %__MODULE__{
    :Spec => DockerEngineAPI.Model.EndpointSpec.t | nil,
    :Ports => [DockerEngineAPI.Model.EndpointPortConfig.t] | nil,
    :VirtualIPs => [DockerEngineAPI.Model.ServiceEndpointVirtualIpsInner.t] | nil
  }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.ServiceEndpoint do
  import DockerEngineAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:Spec, :struct, DockerEngineAPI.Model.EndpointSpec, options)
    |> deserialize(:Ports, :list, DockerEngineAPI.Model.EndpointPortConfig, options)
    |> deserialize(:VirtualIPs, :list, DockerEngineAPI.Model.ServiceEndpointVirtualIpsInner, options)
  end
end

