# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.ServiceEndpointVirtualIpsInner do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :NetworkID,
    :Addr
  ]

  @type t :: %__MODULE__{
    :NetworkID => String.t | nil,
    :Addr => String.t | nil
  }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.ServiceEndpointVirtualIpsInner do
  def decode(value, _options) do
    value
  end
end

