# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.ServiceSpecModeReplicatedJob do
  @moduledoc """
  The mode used for services with a finite number of tasks that run to a completed state. 
  """

  @derive [Poison.Encoder]
  defstruct [
    :MaxConcurrent,
    :TotalCompletions
  ]

  @type t :: %__MODULE__{
    :MaxConcurrent => integer() | nil,
    :TotalCompletions => integer() | nil
  }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.ServiceSpecModeReplicatedJob do
  def decode(value, _options) do
    value
  end
end

