# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.SwarmSpecDispatcher do
  @moduledoc """
  Dispatcher configuration.
  """

  @derive [Poison.Encoder]
  defstruct [
    :HeartbeatPeriod
  ]

  @type t :: %__MODULE__{
    :HeartbeatPeriod => integer() | nil
  }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.SwarmSpecDispatcher do
  def decode(value, _options) do
    value
  end
end

