# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.SwarmInitRequest do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :ListenAddr,
    :AdvertiseAddr,
    :DataPathAddr,
    :DataPathPort,
    :DefaultAddrPool,
    :ForceNewCluster,
    :SubnetSize,
    :Spec
  ]

  @type t :: %__MODULE__{
    :ListenAddr => String.t | nil,
    :AdvertiseAddr => String.t | nil,
    :DataPathAddr => String.t | nil,
    :DataPathPort => integer() | nil,
    :DefaultAddrPool => [String.t] | nil,
    :ForceNewCluster => boolean() | nil,
    :SubnetSize => integer() | nil,
    :Spec => DockerEngineAPI.Model.SwarmSpec.t | nil
  }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.SwarmInitRequest do
  import DockerEngineAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:Spec, :struct, DockerEngineAPI.Model.SwarmSpec, options)
  end
end

