# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.SwarmSpecCaConfig do
  @moduledoc """
  CA configuration.
  """

  @derive [Poison.Encoder]
  defstruct [
    :NodeCertExpiry,
    :ExternalCAs,
    :SigningCACert,
    :SigningCAKey,
    :ForceRotate
  ]

  @type t :: %__MODULE__{
    :NodeCertExpiry => integer() | nil,
    :ExternalCAs => [DockerEngineAPI.Model.SwarmSpecCaConfigExternalCasInner.t] | nil,
    :SigningCACert => String.t | nil,
    :SigningCAKey => String.t | nil,
    :ForceRotate => integer() | nil
  }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.SwarmSpecCaConfig do
  import DockerEngineAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:ExternalCAs, :list, DockerEngineAPI.Model.SwarmSpecCaConfigExternalCasInner, options)
  end
end

