# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.SwarmSpecRaft do
  @moduledoc """
  Raft configuration.
  """

  @derive [Poison.Encoder]
  defstruct [
    :SnapshotInterval,
    :KeepOldSnapshots,
    :LogEntriesForSlowFollowers,
    :ElectionTick,
    :HeartbeatTick
  ]

  @type t :: %__MODULE__{
    :SnapshotInterval => integer() | nil,
    :KeepOldSnapshots => integer() | nil,
    :LogEntriesForSlowFollowers => integer() | nil,
    :ElectionTick => integer() | nil,
    :HeartbeatTick => integer() | nil
  }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.SwarmSpecRaft do
  def decode(value, _options) do
    value
  end
end

