# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.SwarmSpecTaskDefaults do
  @moduledoc """
  Defaults for creating tasks in this cluster.
  """

  @derive [Poison.Encoder]
  defstruct [
    :LogDriver
  ]

  @type t :: %__MODULE__{
    :LogDriver => DockerEngineAPI.Model.SwarmSpecTaskDefaultsLogDriver.t | nil
  }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.SwarmSpecTaskDefaults do
  import DockerEngineAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:LogDriver, :struct, DockerEngineAPI.Model.SwarmSpecTaskDefaultsLogDriver, options)
  end
end

