# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.SwarmAllOf do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :JoinTokens
  ]

  @type t :: %__MODULE__{
    :JoinTokens => DockerEngineAPI.Model.JoinTokens.t | nil
  }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.SwarmAllOf do
  import DockerEngineAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:JoinTokens, :struct, DockerEngineAPI.Model.JoinTokens, options)
  end
end

