# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.SwarmJoinRequest do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :ListenAddr,
    :AdvertiseAddr,
    :DataPathAddr,
    :RemoteAddrs,
    :JoinToken
  ]

  @type t :: %__MODULE__{
    :ListenAddr => String.t | nil,
    :AdvertiseAddr => String.t | nil,
    :DataPathAddr => String.t | nil,
    :RemoteAddrs => [String.t] | nil,
    :JoinToken => String.t | nil
  }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.SwarmJoinRequest do
  def decode(value, _options) do
    value
  end
end

