# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.SwarmSpecCaConfigExternalCasInner do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :Protocol,
    :URL,
    :Options,
    :CACert
  ]

  @type t :: %__MODULE__{
    :Protocol => String.t | nil,
    :URL => String.t | nil,
    :Options => %{optional(String.t) => String.t} | nil,
    :CACert => String.t | nil
  }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.SwarmSpecCaConfigExternalCasInner do
  def decode(value, _options) do
    value
  end
end

