# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.SwarmSpecEncryptionConfig do
  @moduledoc """
  Parameters related to encryption-at-rest.
  """

  @derive [Poison.Encoder]
  defstruct [
    :AutoLockManagers
  ]

  @type t :: %__MODULE__{
    :AutoLockManagers => boolean() | nil
  }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.SwarmSpecEncryptionConfig do
  def decode(value, _options) do
    value
  end
end

