# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.SwarmSpecOrchestration do
  @moduledoc """
  Orchestration configuration.
  """

  @derive [Poison.Encoder]
  defstruct [
    :TaskHistoryRetentionLimit
  ]

  @type t :: %__MODULE__{
    :TaskHistoryRetentionLimit => integer() | nil
  }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.SwarmSpecOrchestration do
  def decode(value, _options) do
    value
  end
end

