# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.Swarm do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :ID,
    :Version,
    :CreatedAt,
    :UpdatedAt,
    :Spec,
    :TLSInfo,
    :RootRotationInProgress,
    :DataPathPort,
    :DefaultAddrPool,
    :SubnetSize,
    :JoinTokens
  ]

  @type t :: %__MODULE__{
    :ID => String.t | nil,
    :Version => DockerEngineAPI.Model.ObjectVersion.t | nil,
    :CreatedAt => String.t | nil,
    :UpdatedAt => String.t | nil,
    :Spec => DockerEngineAPI.Model.SwarmSpec.t | nil,
    :TLSInfo => DockerEngineAPI.Model.TlsInfo.t | nil,
    :RootRotationInProgress => boolean() | nil,
    :DataPathPort => integer() | nil,
    :DefaultAddrPool => [String.t] | nil,
    :SubnetSize => integer() | nil,
    :JoinTokens => DockerEngineAPI.Model.JoinTokens.t | nil
  }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.Swarm do
  import DockerEngineAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:Version, :struct, DockerEngineAPI.Model.ObjectVersion, options)
    |> deserialize(:Spec, :struct, DockerEngineAPI.Model.SwarmSpec, options)
    |> deserialize(:TLSInfo, :struct, DockerEngineAPI.Model.TlsInfo, options)
    |> deserialize(:JoinTokens, :struct, DockerEngineAPI.Model.JoinTokens, options)
  end
end

