# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.SystemDataUsageResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :LayersSize,
    :Images,
    :Containers,
    :Volumes,
    :BuildCache
  ]

  @type t :: %__MODULE__{
    :LayersSize => integer() | nil,
    :Images => [DockerEngineAPI.Model.ImageSummary.t] | nil,
    :Containers => [DockerEngineAPI.Model.ContainerSummary.t] | nil,
    :Volumes => [DockerEngineAPI.Model.Volume.t] | nil,
    :BuildCache => [DockerEngineAPI.Model.BuildCache.t] | nil
  }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.SystemDataUsageResponse do
  import DockerEngineAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:Images, :list, DockerEngineAPI.Model.ImageSummary, options)
    |> deserialize(:Containers, :list, DockerEngineAPI.Model.ContainerSummary, options)
    |> deserialize(:Volumes, :list, DockerEngineAPI.Model.Volume, options)
    |> deserialize(:BuildCache, :list, DockerEngineAPI.Model.BuildCache, options)
  end
end

