# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.SystemAuthResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :Status,
    :IdentityToken
  ]

  @type t :: %__MODULE__{
    :Status => String.t,
    :IdentityToken => String.t | nil
  }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.SystemAuthResponse do
  def decode(value, _options) do
    value
  end
end

