# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.SystemVersion do
  @moduledoc """
  Response of Engine API: GET \"/version\" 
  """

  @derive [Poison.Encoder]
  defstruct [
    :Platform,
    :Components,
    :Version,
    :ApiVersion,
    :MinAPIVersion,
    :GitCommit,
    :GoVersion,
    :Os,
    :Arch,
    :KernelVersion,
    :Experimental,
    :BuildTime
  ]

  @type t :: %__MODULE__{
    :Platform => DockerEngineAPI.Model.SystemVersionPlatform.t | nil,
    :Components => [DockerEngineAPI.Model.SystemVersionComponentsInner.t] | nil,
    :Version => String.t | nil,
    :ApiVersion => String.t | nil,
    :MinAPIVersion => String.t | nil,
    :GitCommit => String.t | nil,
    :GoVersion => String.t | nil,
    :Os => String.t | nil,
    :Arch => String.t | nil,
    :KernelVersion => String.t | nil,
    :Experimental => boolean() | nil,
    :BuildTime => String.t | nil
  }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.SystemVersion do
  import DockerEngineAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:Platform, :struct, DockerEngineAPI.Model.SystemVersionPlatform, options)
    |> deserialize(:Components, :list, DockerEngineAPI.Model.SystemVersionComponentsInner, options)
  end
end

