# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.SystemVersionComponentsInner do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :Name,
    :Version,
    :Details
  ]

  @type t :: %__MODULE__{
    :Name => String.t,
    :Version => String.t,
    :Details => map() | nil
  }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.SystemVersionComponentsInner do
  def decode(value, _options) do
    value
  end
end

