# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.SystemInfoDefaultAddressPoolsInner do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :Base,
    :Size
  ]

  @type t :: %__MODULE__{
    :Base => String.t | nil,
    :Size => integer() | nil
  }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.SystemInfoDefaultAddressPoolsInner do
  def decode(value, _options) do
    value
  end
end

