# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.SystemVersionPlatform do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :Name
  ]

  @type t :: %__MODULE__{
    :Name => String.t
  }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.SystemVersionPlatform do
  def decode(value, _options) do
    value
  end
end

