# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.TaskSpecContainerSpecConfigsInner do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :File,
    :Runtime,
    :ConfigID,
    :ConfigName
  ]

  @type t :: %__MODULE__{
    :File => DockerEngineAPI.Model.TaskSpecContainerSpecConfigsInnerFile.t | nil,
    :Runtime => map() | nil,
    :ConfigID => String.t | nil,
    :ConfigName => String.t | nil
  }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.TaskSpecContainerSpecConfigsInner do
  import DockerEngineAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:File, :struct, DockerEngineAPI.Model.TaskSpecContainerSpecConfigsInnerFile, options)
  end
end

