# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.TaskSpecContainerSpecConfigsInnerFile do
  @moduledoc """
  File represents a specific target that is backed by a file.  <p><br /><p>  > **Note**: `Configs.File` and `Configs.Runtime` are mutually exclusive 
  """

  @derive [Poison.Encoder]
  defstruct [
    :Name,
    :UID,
    :GID,
    :Mode
  ]

  @type t :: %__MODULE__{
    :Name => String.t | nil,
    :UID => String.t | nil,
    :GID => String.t | nil,
    :Mode => integer() | nil
  }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.TaskSpecContainerSpecConfigsInnerFile do
  def decode(value, _options) do
    value
  end
end

