# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.TaskSpecPluginSpec do
  @moduledoc """
  Plugin spec for the service.  *(Experimental release only.)*  <p><br /></p>  > **Note**: ContainerSpec, NetworkAttachmentSpec, and PluginSpec are > mutually exclusive. PluginSpec is only used when the Runtime field > is set to `plugin`. NetworkAttachmentSpec is used when the Runtime > field is set to `attachment`. 
  """

  @derive [Poison.Encoder]
  defstruct [
    :Name,
    :Remote,
    :Disabled,
    :PluginPrivilege
  ]

  @type t :: %__MODULE__{
    :Name => String.t | nil,
    :Remote => String.t | nil,
    :Disabled => boolean() | nil,
    :PluginPrivilege => [DockerEngineAPI.Model.PluginPrivilege.t] | nil
  }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.TaskSpecPluginSpec do
  import DockerEngineAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:PluginPrivilege, :list, DockerEngineAPI.Model.PluginPrivilege, options)
  end
end

