# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.TaskSpecPlacement do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :Constraints,
    :Preferences,
    :MaxReplicas,
    :Platforms
  ]

  @type t :: %__MODULE__{
    :Constraints => [String.t] | nil,
    :Preferences => [DockerEngineAPI.Model.TaskSpecPlacementPreferencesInner.t] | nil,
    :MaxReplicas => integer() | nil,
    :Platforms => [DockerEngineAPI.Model.Platform.t] | nil
  }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.TaskSpecPlacement do
  import DockerEngineAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:Preferences, :list, DockerEngineAPI.Model.TaskSpecPlacementPreferencesInner, options)
    |> deserialize(:Platforms, :list, DockerEngineAPI.Model.Platform, options)
  end
end

