# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.TaskSpecContainerSpecPrivilegesSeLinuxContext do
  @moduledoc """
  SELinux labels of the container
  """

  @derive [Poison.Encoder]
  defstruct [
    :Disable,
    :User,
    :Role,
    :Type,
    :Level
  ]

  @type t :: %__MODULE__{
    :Disable => boolean() | nil,
    :User => String.t | nil,
    :Role => String.t | nil,
    :Type => String.t | nil,
    :Level => String.t | nil
  }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.TaskSpecContainerSpecPrivilegesSeLinuxContext do
  def decode(value, _options) do
    value
  end
end

