# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.TaskSpecPlacementPreferencesInner do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :Spread
  ]

  @type t :: %__MODULE__{
    :Spread => DockerEngineAPI.Model.TaskSpecPlacementPreferencesInnerSpread.t | nil
  }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.TaskSpecPlacementPreferencesInner do
  import DockerEngineAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:Spread, :struct, DockerEngineAPI.Model.TaskSpecPlacementPreferencesInnerSpread, options)
  end
end

