# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.Task do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :ID,
    :Version,
    :CreatedAt,
    :UpdatedAt,
    :Name,
    :Labels,
    :Spec,
    :ServiceID,
    :Slot,
    :NodeID,
    :AssignedGenericResources,
    :Status,
    :DesiredState,
    :JobIteration
  ]

  @type t :: %__MODULE__{
    :ID => String.t | nil,
    :Version => DockerEngineAPI.Model.ObjectVersion.t | nil,
    :CreatedAt => String.t | nil,
    :UpdatedAt => String.t | nil,
    :Name => String.t | nil,
    :Labels => %{optional(String.t) => String.t} | nil,
    :Spec => DockerEngineAPI.Model.TaskSpec.t | nil,
    :ServiceID => String.t | nil,
    :Slot => integer() | nil,
    :NodeID => String.t | nil,
    :AssignedGenericResources => [DockerEngineAPI.Model.GenericResourcesInner.t] | nil,
    :Status => DockerEngineAPI.Model.TaskStatus.t | nil,
    :DesiredState => DockerEngineAPI.Model.TaskState.t | nil,
    :JobIteration => DockerEngineAPI.Model.ObjectVersion.t | nil
  }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.Task do
  import DockerEngineAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:Version, :struct, DockerEngineAPI.Model.ObjectVersion, options)
    |> deserialize(:Spec, :struct, DockerEngineAPI.Model.TaskSpec, options)
    |> deserialize(:AssignedGenericResources, :list, DockerEngineAPI.Model.GenericResourcesInner, options)
    |> deserialize(:Status, :struct, DockerEngineAPI.Model.TaskStatus, options)
    |> deserialize(:DesiredState, :struct, DockerEngineAPI.Model.TaskState, options)
    |> deserialize(:JobIteration, :struct, DockerEngineAPI.Model.ObjectVersion, options)
  end
end

