# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.TaskSpecContainerSpecPrivileges do
  @moduledoc """
  Security options for the container
  """

  @derive [Poison.Encoder]
  defstruct [
    :CredentialSpec,
    :SELinuxContext
  ]

  @type t :: %__MODULE__{
    :CredentialSpec => DockerEngineAPI.Model.TaskSpecContainerSpecPrivilegesCredentialSpec.t | nil,
    :SELinuxContext => DockerEngineAPI.Model.TaskSpecContainerSpecPrivilegesSeLinuxContext.t | nil
  }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.TaskSpecContainerSpecPrivileges do
  import DockerEngineAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:CredentialSpec, :struct, DockerEngineAPI.Model.TaskSpecContainerSpecPrivilegesCredentialSpec, options)
    |> deserialize(:SELinuxContext, :struct, DockerEngineAPI.Model.TaskSpecContainerSpecPrivilegesSeLinuxContext, options)
  end
end

