# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.TaskSpecContainerSpecDnsConfig do
  @moduledoc """
  Specification for DNS related configurations in resolver configuration file (`resolv.conf`). 
  """

  @derive [Poison.Encoder]
  defstruct [
    :Nameservers,
    :Search,
    :Options
  ]

  @type t :: %__MODULE__{
    :Nameservers => [String.t] | nil,
    :Search => [String.t] | nil,
    :Options => [String.t] | nil
  }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.TaskSpecContainerSpecDnsConfig do
  def decode(value, _options) do
    value
  end
end

