# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.TaskSpecResources do
  @moduledoc """
  Resource requirements which apply to each individual container created as part of the service. 
  """

  @derive [Poison.Encoder]
  defstruct [
    :Limits,
    :Reservations
  ]

  @type t :: %__MODULE__{
    :Limits => DockerEngineAPI.Model.Limit.t | nil,
    :Reservations => DockerEngineAPI.Model.ResourceObject.t | nil
  }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.TaskSpecResources do
  import DockerEngineAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:Limits, :struct, DockerEngineAPI.Model.Limit, options)
    |> deserialize(:Reservations, :struct, DockerEngineAPI.Model.ResourceObject, options)
  end
end

