# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.TlsInfo do
  @moduledoc """
  Information about the issuer of leaf TLS certificates and the trusted root CA certificate. 
  """

  @derive [Poison.Encoder]
  defstruct [
    :TrustRoot,
    :CertIssuerSubject,
    :CertIssuerPublicKey
  ]

  @type t :: %__MODULE__{
    :TrustRoot => String.t | nil,
    :CertIssuerSubject => String.t | nil,
    :CertIssuerPublicKey => String.t | nil
  }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.TlsInfo do
  def decode(value, _options) do
    value
  end
end

