# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.Volume do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :Name,
    :Driver,
    :Mountpoint,
    :CreatedAt,
    :Status,
    :Labels,
    :Scope,
    :Options,
    :UsageData
  ]

  @type t :: %__MODULE__{
    :Name => String.t,
    :Driver => String.t,
    :Mountpoint => String.t,
    :CreatedAt => String.t | nil,
    :Status => %{optional(String.t) => map()} | nil,
    :Labels => %{optional(String.t) => String.t},
    :Scope => String.t,
    :Options => %{optional(String.t) => String.t},
    :UsageData => DockerEngineAPI.Model.VolumeUsageData.t | nil
  }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.Volume do
  import DockerEngineAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:UsageData, :struct, DockerEngineAPI.Model.VolumeUsageData, options)
  end
end

