# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.VolumeListResponse do
  @moduledoc """
  Volume list response
  """

  @derive [Poison.Encoder]
  defstruct [
    :Volumes,
    :Warnings
  ]

  @type t :: %__MODULE__{
    :Volumes => [DockerEngineAPI.Model.Volume.t],
    :Warnings => [String.t]
  }
end

defimpl Poison.Decoder, for: DockerEngineAPI.Model.VolumeListResponse do
  import DockerEngineAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:Volumes, :list, DockerEngineAPI.Model.Volume, options)
  end
end

